name: Build LKM for Custom Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-lkm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up swap space
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab
          sudo sysctl vm.swappiness=10
          sudo sysctl vm.vfs_cache_pressure=50

      - name: Download GCC toolchain
        run: |
          curl -L https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz -o toolchain.tar.gz
          mkdir -p toolchain
          tar -xzvf toolchain.tar.gz -C toolchain --strip-components=1
          rm toolchain.tar.gz

      - name: Set up GCC environment
        run: |
          export PATH=$PWD/toolchain/bin:$PATH
          export CC=aarch64-linux-android-gcc
          export LD=aarch64-linux-android-ld
          export CROSS_COMPILE=aarch64-linux-android-

      - name: Set up kernel environment
        run: |
          git clone https://github.com/Yuyuko1024/kernel_xiaomi_chopin.git
          cd kernel_xiaomi_chopin
          git checkout chopin-r-oss
          export ARCH=arm64
          export SUBARCH=arm64
          cp arch/arm64/configs/chopin_user_defconfig .config
          make olddefconfig

      - name: Build LKM
        run: |
          cd kernel_xiaomi_chopin
          make ARCH=arm64 SUBARCH=arm64 modules

      - name: Upload kernel modules
        uses: actions/upload-artifact@v2
        with:
          name: kernel_modules
          path: kernel_xiaomi_chopin/*.ko

      - name: Clean up workspace
        run: |
          cd ..
          rm -rf kernel_xiaomi_chopin
          rm -rf toolchain

      # Add any additional steps as needed, such as testing or deploying the LKM
